"""status column type changing

Revision ID: a11adac6b5f6
Revises: a1b2c3d4e5f6
Create Date: 2026-06-18 10:10:43.553428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a11adac6b5f6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ENUM_NAME = "phrasestatusenum"
_ENUM_VALUES = (
    "draft",
    "generating_in_progress", "generating_done", "generating_failed",
    "translating_in_progress", "translating_done", "translating_failed",
    "embedding_in_progress", "embedding_done", "embedding_failed",
    "loading_in_progress", "loading_done", "loading_failed",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phrases', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'GENERATING_IN_PROGRESS', 'GENERATING_DONE', 'GENERATING_FAILED', 'TRANSLATING_IN_PROGRESS', 'TRANSLATING_DONE', 'TRANSLATING_FAILED', 'EMBEDDING_IN_PROGRESS', 'EMBEDDING_DONE', 'EMBEDDING_FAILED', 'LOADING_IN_PROGRESS', 'LOADING_DONE', 'LOADING_FAILED', name='phrasestatusenum'),
               existing_comment='Статус обработки',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phrases', 'status',
               existing_type=sa.Enum('DRAFT', 'GENERATING_IN_PROGRESS', 'GENERATING_DONE', 'GENERATING_FAILED', 'TRANSLATING_IN_PROGRESS', 'TRANSLATING_DONE', 'TRANSLATING_FAILED', 'EMBEDDING_IN_PROGRESS', 'EMBEDDING_DONE', 'EMBEDDING_FAILED', 'LOADING_IN_PROGRESS', 'LOADING_DONE', 'LOADING_FAILED', name='phrasestatusenum'),
               type_=sa.VARCHAR(length=30),
               existing_comment='Статус обработки',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    # ### end Alembic commands ###
