"""add_phrases_table

Revision ID: 8338b7abf931
Revises: 
Create Date: 2026-06-15 10:58:25.043707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8338b7abf931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('original', sa.String(), nullable=False, comment='Фраза в lowercase без знаков препинания'),
    sa.Column('tag', sa.String(length=20), nullable=False, comment='Тег наблюдения'),
    sa.Column('lang', sa.String(length=2), server_default=sa.text("'ru'"), nullable=False, comment='Язык фразы'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='Статус обработки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False, comment='Время обновления записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original', 'lang', name='uq_phrases_original_lang'),
    comment='Оригинальные фразы-наблюдения, полученные от vision-модели'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrases')
    # ### end Alembic commands ###
