"""expand_phrases_status_column

Revision ID: f0984b31be32
Revises: 8338b7abf931
Create Date: 2026-06-15 12:10:13.232331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f0984b31be32"
down_revision: Union[str, Sequence[str], None] = "8338b7abf931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phrases",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_comment="Статус обработки",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phrases",
        "status",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_comment="Статус обработки",
        existing_nullable=False,
        existing_server_default=sa.text("'draft'::character varying"),
    )
    # ### end Alembic commands ###
