"""add_phrase_data_table

Revision ID: df19b82e52c4
Revises: f0984b31be32
Create Date: 2026-06-16 09:29:06.940080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "df19b82e52c4"
down_revision: Union[str, Sequence[str], None] = "f0984b31be32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phrase_data",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "phrase_id",
            sa.BigInteger(),
            nullable=False,
            comment="FK на оригинальную фразу",
        ),
        sa.Column(
            "variants",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Варианты по настроению: {"A": {"male": [...5...], "female": [...5...]}, ...}',
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
            comment="Время обновления записи",
        ),
        sa.ForeignKeyConstraint(["phrase_id"], ["phrases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phrase_id"),
        comment="Варианты фраз по настроению и полу, staging перед загрузкой в Qdrant",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phrase_data")
    # ### end Alembic commands ###
